Refactoring/book form 249
Project-Books/book-project pull request #324
Opened 2020-09-08 08:33 UTC by kaansonmezoz

## Summary of change

Refactored `BookForm.class`

- Splitted populateBookBean() into phases

    validations etc.    

- Extracted Form items into its own classes & pulled up common methods into a parent class

    
## Related issue
[ISSUE-249](https://github.com/knjk04/book-project/issues/249)

## Pull request checklist

Please ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
- [x] Ensure that you were first assigned to a relevant issue before creating this pull request
- [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
- [x] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

If in doubt, get in touch with us via our [Gitter room](https://gitter.im/book-project-community/community)

2020-09-08 18:41 UTC, knjk04 commented
As you may have seen on our Gitter group chat, we've moved the repository from my personal account to an organisation. Could you update the remote for your local fork, please?

$ git remote set-url origin https://github.com/Project-Books/book-project

2020-09-09 16:52 UTC, kaansonmezoz commented
> As you may have seen on our Gitter group chat, we've moved the repository from my personal account to an organisation. Could you update the remote for your local fork, please?
> 
> $ git remote set-url origin https://github.com/Project-Books/book-project

Sure. I've not joined Gitter yet, but I had better to join as soon as possible :slightly_smiling_face:

2020-09-09 17:15 UTC, knjk04 commented
Thanks. Just so you know, we're moving from Gitter to Slack, so if you see a Slack link, follow that instead

2020-09-13 09:13 UTC, knjk04 requested changes
Thanks for working on this! 

I've left some preliminary comments. When you're ready for another review, let us know.

2020-09-13 09:13 UTC, knjk04 commented on src/main/java/com/karankumar/bookproject/ui/book/BookForm.java
> +import com.karankumar.bookproject.ui.book.components.form.item.visible.*;
Please note that, as per our style guide, we're not using wildcard imports.

2020-09-13 09:13 UTC, knjk04 commented on src/main/java/com/karankumar/bookproject/ui/book/components/form/item/AuthorFirstName.java
> +    private SerializablePredicate<String> authorPredicate() {
Could you please change the name of this method so that is more descriptive (e.g. `isAuthorFieldPopulated()`)?

2020-09-13 09:13 UTC, knjk04 commented on src/main/java/com/karankumar/bookproject/ui/book/components/form/item/AuthorLastName.java
> +    }
We have the same predicate for the author's first name, so could you use that one instead of redefining it?

2020-09-13 09:13 UTC, knjk04 commented on src/main/java/com/karankumar/bookproject/ui/book/components/form/item/visible/SeriesPosition.java
> +    }
We have this same predicate for `PageCount`, so we could reuse that one

2020-09-19 06:18 UTC, knjk04 commented
A number of changes have been made, so I would recommend rebasing

2020-09-23 13:34 UTC, knjk04 commented
@kaansonmezoz How are you getting on with the changes?

2020-10-01 06:53 UTC, knjk04 commented
@kaansonmezoz do you have an update on the progress of this PR?

As ever, if you need anything, feel free to get in touch with us over [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

2020-10-16 16:30 UTC, knjk04 commented
@kaansonmezoz Do you have an update on the progress of this? I know you sent a Slack message a couple of weeks ago

2020-10-28 08:00 UTC, knjk04 commented
@kaansonmezoz As we have not heard from you in a while, despite following up, I'll close this pull request

2020-10-28 08:00 UTC, closed without merging