Add float point division in PageStatictics
Project-Books/book-project pull request #404
Opened 2020-10-03 16:18 UTC by ShreyaPrabhu

## Summary of change
Add float point division in Page Statistics file to the average page length calculation function.

## Additional context
Added a test case as well to verify above mentioned change. 
Test case description - 
Initial setup -
Total Number of pages = 1750 
Total Number of books = 7
I deleted one book with number of pages 150 to make get following new values - 
Total Number of pages =1600 
Total Number of books = 6
Division result = 266.66 
After Math.ceil(266.66) = 267

I have made changes to clear savedBooks list and reset totalRating to 0.0 in populateReadBooks function under StatisticTestUtils.java file. I noticed that every time bookService.deleteAll() was called, though it cleared the repository, it did not clear the list or reset total rating which is expected behavior. 

Ran all test cases to make sure no other test cases failed due to the changes made in this PR.

[If a screenshot would be useful (e.g. for UI changes), please provide one.]

## Related issue

Closes #399 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [ ] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [ ] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [ ] Ensure code changes pass all tests

- [ ] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [ ] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [ ] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [ ] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [ ] Set this pull request to 'draft' if you are still working on it

- [ ] Resolved any merge conflicts

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-h6vx3n8l-KN8QnO50r7QWZHgHFnFdPw)

2020-10-03 16:27 UTC, ShreyaPrabhu commented
@knjk04 This PR is ready for review. I was not able to add reviewers or mark the PR as ready to review. Hence commenting here.

2020-10-04 05:45 UTC, knjk04 commented
@ShreyaPrabhu Thanks, we'll review it shortly

2020-10-05 17:32 UTC, knjk04 requested changes
Thanks for working on this! I've left some feedback for improvements

2020-10-05 17:32 UTC, knjk04 commented on src/main/java/com/karankumar/bookproject/backend/statistics/PageStatistics.java
> +                (int) Math.ceil(totalNumberOfPages / (float) booksWithPagesSpecified);
Could you please remove the `int` cast? I think it's better to return float here (sorry, I should have mentioned this in the issue)

2020-10-05 17:32 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/statistics/PageStatisticsTest.java
> +        int averagePageLength = (int) Math.ceil(StatisticTestUtils.getTotalNumberOfPages() / (float) StatisticTestUtils.getNumberOfBooks());
Could you please ensure this line adheres to our 100 character column limit?

2020-10-05 17:32 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/statistics/PageStatisticsTest.java
> +    void averagePageLengthWhenRoundedToHigherNumber() {
Could you please rename this method to better reflect what is being tested?

2020-10-05 17:32 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/statistics/PageStatisticsTest.java
> +        int averagePageLength = (int) Math.ceil(StatisticTestUtils.getTotalNumberOfPages() / (float) StatisticTestUtils.getNumberOfBooks());
Also, could you please replace this line with a hardcoded value? I think the problem with the current approach is that we're redefining the code under test, so this should always pass.

2020-10-05 17:32 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/statistics/utils/StatisticTestUtils.java
> +        bookToDelete.setPredefinedShelf(readShelf);
I don't think these first two lines are needed

2020-10-06 15:09 UTC, knjk04 commented
Let us know when you're ready for another review

2020-10-06 15:12 UTC, ShreyaPrabhu commented
@knjk04 This is ready for review. Have made the changes requested.

2020-10-07 15:09 UTC, knjk04 commented
@ShreyaPrabhu Could you please resolve the merge conflict?

2020-10-07 15:41 UTC, ShreyaPrabhu commented
@knjk04 Merge conflict was present in one file. It has been resolved.

2020-10-07 18:21 UTC, knjk04 approved these changes

2020-10-07 18:22 UTC, knjk04 commented
@ShreyaPrabhu Thank you for working on this!

2020-10-07 18:22 UTC, merged