Refactor tests to include DisplayNames and better method names
Project-Books/book-project pull request #484
Opened 2020-10-17 17:26 UTC by schrothbn

## Summary of change

Refactored all tests (if necessary) to include DisplayNames for classes and better method names

## Additional context

## Related issue

Closes #411 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request
  - [ ] Included a screenshot(s) if a UI change was involved (it may look different on a reviewer's device)

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [ ] Set this pull request to 'draft' if you are still working on it

- [ ] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

2020-10-17 17:40 UTC, knjk04 commented
@schrothbn Thanks again for the quick turnaround from being assigned to creating the PR! We'll review this shortly

2020-10-18 13:51 UTC, knjk04 requested changes
Thanks a lot for doing this! I've left some review feedback

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/entity/account/UserTest.java
> +    void beSaved() {
How about adding `ifValid` to the end of this?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/goal/CalculateReadingGoalTest.java
> +    void calculateProgressValueCorrect() {
How about changing this to `calculateCorrectProgressValue`?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/goal/CalculateReadingGoalTest.java
> +    void calculateProgressValueCorrectWhenGoaldMet() {
What about `calculateCorrectProgressValueWhenGoalMet`?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/goal/CalculateReadingGoalTest.java
> +    void calculateProgressValueCorrectWhenGOalExceeded() {
The 'O' in 'Goal' should be lowercase

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/repository/CustomShelfRepositoryTest.java
>      void findByShelfNameCorrectlyReturnsOneShelf() {
Could you please rename to 'findCorrectShelf'?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/repository/PredefinedShelfRepositoryTest.java
> +    void correctlyReturnExistingShelf() {
Could you please rename this to something like 'findCorrectShelf'?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/service/BookServiceTest.java
> +    void notSaveBookWithout() {
I think you forgot 'Author' at the end of this?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/service/UserServiceTest.java
> +    void registerUser() {
How about `registerValidUser` (I know the name before didn't have this, but I think this is clearer)?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/statistics/GenreStatisticsTest.java
> +    void findExistingMostReadGenre() {
What about `findMostReadGenre()`?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/statistics/GenreStatisticsTest.java
> +    void findMostLikedGenreExists() {
What about `findMostLikedGenre()`?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/statistics/PageStatisticsTest.java
> +    void coundOnlyReadBooksTowardsMostPagesStatistics() {
Typo here: this should be 'count' at the start

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/statistics/RatingStatisticsTest.java
> +    void findLowestRatedBookExists() {
Could you please remove 'Exists'?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/utils/CustomShelfUtilsTest.java
> +    void returnEmptySetOfBooksWhenCustomShelfIsInvalid() {
Could you please rename this to 'returnEmptySetofBooksFromNonExistentCustomShelf'?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/ui/book/BookFormTest.java
> +    void populateCorrectlyFieldsToReset(
Could you please move 'Correctly' to the end (so we get 'populateFieldsToResetCorrectly')?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/ui/book/BookFormTest.java
> +    void notAllowToExceedMaxValueNumberOfPagesField() {
Could you please rename to 'notAllowPagesFieldToExceedMaxValue'?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/ui/book/BookFormTest.java
> +    void notAllowToExceedMaxValueToPagesRead() {
Could you please rename to 'notAllowPagesReadToExceedMaxValue'?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/ui/book/BookFormTest.java
> +    void shouldSaveChangedAuthorName() {
As we already have 'should' in the class's display name, could you please rename this to 'saveChangedAuthorName'?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/ui/registration/RegistrationFormTest.java
> +    void setErrorOnPasswordConfirmationWrong() {
Could you please rename this to 'showErrorWhenPasswordConfirmationIsWrong'?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/ui/registration/RegistrationFormTest.java
> +    void setErrorOnPasswordFieldNotMatchingTheRules() {
Could you please change the 'setError' prefix to 'showError'?

2020-10-18 13:51 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/ui/shelf/CustomShelfFormTest.java
> +    void disableSaveButtonInitiallyWithExistingShelfName () {
Could you please remove 'Initially' here?

2020-10-18 13:57 UTC, knjk04 requested changes
A few more comments

2020-10-18 13:57 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/service/UserServiceTest.java
> +    void logsUserInAfterRegister() {
Could you please remove the 's' from 'logs'?

2020-10-18 13:57 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/service/UserServiceTest.java
> +    void checksIfUserNameIsInUseWithUsernameNotInUse() {
How about 'correctlyReportUsernameIsNotInUse'?

2020-10-18 13:57 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/service/UserServiceTest.java
> +    void checksIfUserNameIsInUseWithUsernameInUse() {
How about 'correctlyReportUsernameIsInUse'?

2020-10-18 13:57 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/service/UserServiceTest.java
> +    void checkIfEmailIsInUseWithEmailNotInUse() {
How about 'correctlyReportEmailIsNotInUse'?

2020-10-18 13:57 UTC, knjk04 commented on src/test/java/com/karankumar/bookproject/backend/service/UserServiceTest.java
> +    void checkIfEmailIsInUseWithEmailInUse() {
How about 'correctlyReportEmailIsInUse'?

2020-10-18 14:54 UTC, knjk04 commented
Also, could you please resolve the merge conflicts? I know there are lots, so I'd like to merge this PR in as soon as possible

2020-10-18 15:06 UTC, schrothbn commented
> Also, could you please resolve the merge conflicts? I know there are lots, so I'd like to merge this PR in as soon as possible.
> 
> When you're ready for another review, let us know

Of course i'm on it. I didn't notice before my push, sorry.

2020-10-18 15:36 UTC, knjk04 approved these changes
Thanks for working on this! I appreciate there were lots of files and changes to make!

2020-10-18 15:37 UTC, merged