Implement book list sorting mechanism
Project-Books/book-project pull request #860
Opened 2021-11-23 18:15 UTC by LoicB

## Summary of change

Add the feature of sorting book when clicking on the column header.
After clicking once, the books are sorted in ascending order.
After clicking twice, the books are sorted in descending order.
Then the books are not sorted anymore.

If you click on two columns both will be applied.

This is when the books are displayed as a list.

## Additional context

![image](https://user-images.githubusercontent.com/622115/143079750-e1cf243b-701c-4a23-8427-c864ede9d60c.png)

![image](https://user-images.githubusercontent.com/622115/143079711-1b1eced0-fed8-41b7-bdee-8b69c76a8cd9.png)

## Related issue

Closes #778

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

2021-12-20 17:01 UTC, knjk04 requested changes
![image](https://user-images.githubusercontent.com/11173328/146804539-1d4ca837-4877-4a11-94fc-fc27f5fe383d.png)

So sorry for the delay, this slipped past me.

Thanks for working on adding the sorting mechanism! This works well for author, shelf & genre. However, it doesn't seem to work for ratings. Could you please look into this?

2022-01-08 08:30 UTC, knjk04 commented
@LoicB How are you getting on with this?

2022-01-08 10:26 UTC, LoicB commented
Hi @knjk04 
Sorry for the late answer.
I improved the sorting algorithm for ratings. 
At the moment the rated book will be first and the not rated ones are after.
Is that ok?

<img width="1016" alt="Screenshot 2022-01-08 at 10 24 15" src="https://user-images.githubusercontent.com/622115/148640783-b36e165b-b0fb-4053-8752-a10fa8804e0d.png">

<img width="1036" alt="Screenshot 2022-01-08 at 10 25 11" src="https://user-images.githubusercontent.com/622115/148640788-9f602768-19b8-409b-a38f-9517564efc91.png">

2022-01-08 16:43 UTC, knjk04 approved these changes
Thank you very much! The sort by ratings works well

2022-01-08 16:43 UTC, merged